apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebcalculator-deployment
  labels:
    app: javawebcalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebcalculator
  template:
    metadata:
      labels:
        app: javawebcalculator
    spec:
      containers:
        - name: javawebcalculator
          image: vmns/dockerdcicd
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebcalculator-service
spec:
  selector:
    app: javawebcalculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
